artifacts_root : artifacts 

data_ingestion :
  root_dir : artifacts/data_ingestion 
  source_URL: https://github.com/krishnaik06/datasets/raw/refs/heads/main/summarizer-data.zip # download the dataset zip here 
  unzip_dir: artifacts/data_ingestion  # unzip here 
  local_data_files: artifacts/data_ingestion/data.zip

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail

ModelTrainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/samsum_dataset
  model_ckpt: google/pegasus-cnn_dailymail

ModelEvaluation:
  root_dir: artifacts/model_eval
  data_path: artifacts/data_transformation/samsum_dataset
  model_path: artifacts/model_trainer/pegasus-samsum-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metric.csv
  

